version: "3.9"

services:
  server:
    container_name: server-backend-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev  # Use development Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app  # Bind mount for live code updates
      - /app/node_modules  # Avoid overwriting node_modules
    env_file:
      - ./server/.env.local  # Development-specific environment variables
    restart: always
    networks:
      - rmit-store-network

  client:
    container_name: client-frontend-dev
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile.dev  # Use development Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app  # Bind mount for live code updates
      - ./client/.env.local:/app/.env  # Mount the .env.local file as .env in the container
      - /app/node_modules  # Avoid overwriting node_modules
    env_file:
      - ./client/.env.local  # Development-specific environment variables
    restart: always
    networks:
      - rmit-store-network

networks:
  rmit-store-network:
    driver: bridge
